[2023-10-16T15:31:33.626+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching.not_eligible_to_drive manual__2023-10-16T14:31:29.005249+00:00 [queued]>
[2023-10-16T15:31:33.628+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching.not_eligible_to_drive manual__2023-10-16T14:31:29.005249+00:00 [queued]>
[2023-10-16T15:31:33.628+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-16T15:31:33.632+0100] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): not_eligible_to_drive> on 2023-10-16 14:31:29.005249+00:00
[2023-10-16T15:31:33.634+0100] {standard_task_runner.py:57} INFO - Started process 1856 to run task
[2023-10-16T15:31:33.636+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'branching', 'not_eligible_to_drive', 'manual__2023-10-16T14:31:29.005249+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/branching.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmpvdpz87mb']
[2023-10-16T15:31:33.637+0100] {standard_task_runner.py:85} INFO - Job 104: Subtask not_eligible_to_drive
[2023-10-16T15:31:33.649+0100] {task_command.py:416} INFO - Running <TaskInstance: branching.not_eligible_to_drive manual__2023-10-16T14:31:29.005249+00:00 [running]> on host 192.168.1.112
[2023-10-16T15:31:33.674+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='workflow' AIRFLOW_CTX_DAG_ID='branching' AIRFLOW_CTX_TASK_ID='not_eligible_to_drive' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T14:31:29.005249+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-16T14:31:29.005249+00:00'
[2023-10-16T15:31:33.675+0100] {logging_mixin.py:151} INFO - Not eligible to drive
[2023-10-16T15:31:33.675+0100] {python.py:194} INFO - Done. Returned value was: None
[2023-10-16T15:31:33.677+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=branching, task_id=not_eligible_to_drive, execution_date=20231016T143129, start_date=20231016T143133, end_date=20231016T143133
[2023-10-16T15:31:33.694+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T15:31:33.699+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
