[2023-10-15T18:12:26.837+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python.greet_person manual__2023-10-15T17:12:25.441289+00:00 [queued]>
[2023-10-15T18:12:26.840+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python.greet_person manual__2023-10-15T17:12:25.441289+00:00 [queued]>
[2023-10-15T18:12:26.840+0100] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-10-15T18:12:26.840+0100] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-10-15T18:12:26.840+0100] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-10-15T18:12:26.845+0100] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet_person> on 2023-10-15 17:12:25.441289+00:00
[2023-10-15T18:12:26.846+0100] {standard_task_runner.py:55} INFO - Started process 57614 to run task
[2023-10-15T18:12:26.856+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python', 'greet_person', 'manual__2023-10-15T17:12:25.441289+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/execute_py.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmp30rha8xf']
[2023-10-15T18:12:26.857+0100] {standard_task_runner.py:83} INFO - Job 42: Subtask greet_person
[2023-10-15T18:12:26.878+0100] {task_command.py:389} INFO - Running <TaskInstance: execute_python.greet_person manual__2023-10-15T17:12:25.441289+00:00 [running]> on host 192.168.1.112
[2023-10-15T18:12:26.899+0100] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=workflow
AIRFLOW_CTX_DAG_ID=execute_python
AIRFLOW_CTX_TASK_ID=greet_person
AIRFLOW_CTX_EXECUTION_DATE=2023-10-15T17:12:25.441289+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-10-15T17:12:25.441289+00:00
[2023-10-15T18:12:26.899+0100] {logging_mixin.py:137} INFO - Hello Bob
[2023-10-15T18:12:26.899+0100] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/b/airflow/dags/execute_py.py", line 29, in greet_person
    print(f'Hello {name}').format(name=name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'format'
[2023-10-15T18:12:26.902+0100] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=execute_python, task_id=greet_person, execution_date=20231015T171225, start_date=20231015T171226, end_date=20231015T171226
[2023-10-15T18:12:26.905+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 42 for task greet_person ('NoneType' object has no attribute 'format'; 57614)
[2023-10-15T18:12:26.909+0100] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-10-15T18:12:26.916+0100] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
