[2023-10-16T01:02:49.966+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute.taskC scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T01:02:49.969+0100] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute.taskC scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-10-16T01:02:49.969+0100] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-10-16T01:02:49.969+0100] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-10-16T01:02:49.969+0100] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-10-16T01:02:49.973+0100] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): taskC> on 2023-10-15 00:00:00+00:00
[2023-10-16T01:02:49.974+0100] {standard_task_runner.py:55} INFO - Started process 72418 to run task
[2023-10-16T01:02:49.976+0100] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'execute', 'taskC', 'scheduled__2023-10-15T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/execute.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmpf_sqkxj4']
[2023-10-16T01:02:49.977+0100] {standard_task_runner.py:83} INFO - Job 61: Subtask taskC
[2023-10-16T01:02:49.994+0100] {task_command.py:389} INFO - Running <TaskInstance: execute.taskC scheduled__2023-10-15T00:00:00+00:00 [running]> on host 192.168.1.112
[2023-10-16T01:02:50.007+0100] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=workflow
AIRFLOW_CTX_DAG_ID=execute
AIRFLOW_CTX_TASK_ID=taskC
AIRFLOW_CTX_EXECUTION_DATE=2023-10-15T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-15T00:00:00+00:00
[2023-10-16T01:02:50.008+0100] {subprocess.py:63} INFO - Tmp dir root location: 
 /var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T
[2023-10-16T01:02:50.008+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK C has started!\nsleep 10\nexit 130\necho TASK C has finished!']
[2023-10-16T01:02:50.011+0100] {subprocess.py:86} INFO - Output:
[2023-10-16T01:02:50.012+0100] {subprocess.py:93} INFO - TASK C has started!
[2023-10-16T01:03:00.022+0100] {subprocess.py:97} INFO - Command exited with return code 130
[2023-10-16T01:03:00.053+0100] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2023-10-16T01:03:00.058+0100] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=execute, task_id=taskC, execution_date=20231015T000000, start_date=20231016T000249, end_date=20231016T000300
[2023-10-16T01:03:00.068+0100] {standard_task_runner.py:100} ERROR - Failed to execute job 61 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 72418)
[2023-10-16T01:03:00.085+0100] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-10-16T01:03:00.101+0100] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
