[2023-10-17T13:40:19.278+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute.taskC scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T13:40:19.281+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute.taskC scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-10-17T13:40:19.281+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T13:40:19.286+0100] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): taskC> on 2023-10-16 00:00:00+00:00
[2023-10-17T13:40:19.287+0100] {standard_task_runner.py:57} INFO - Started process 48176 to run task
[2023-10-17T13:40:19.290+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute', 'taskC', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '319', '--raw', '--subdir', 'DAGS_FOLDER/execute.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmpfu4wqyhx']
[2023-10-17T13:40:19.292+0100] {standard_task_runner.py:85} INFO - Job 319: Subtask taskC
[2023-10-17T13:40:19.325+0100] {task_command.py:416} INFO - Running <TaskInstance: execute.taskC scheduled__2023-10-16T00:00:00+00:00 [running]> on host 192.168.1.112
[2023-10-17T13:40:19.347+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='workflow' AIRFLOW_CTX_DAG_ID='execute' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-10-17T13:40:19.347+0100] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T
[2023-10-17T13:40:19.348+0100] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo TASK C has started!\nsleep 10\nexit 130\necho TASK C has finished!']
[2023-10-17T13:40:19.351+0100] {subprocess.py:86} INFO - Output:
[2023-10-17T13:40:19.353+0100] {subprocess.py:93} INFO - TASK C has started!
[2023-10-17T13:40:29.362+0100] {subprocess.py:97} INFO - Command exited with return code 130
[2023-10-17T13:40:29.378+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/b/airflow/venv/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 130.
[2023-10-17T13:40:29.386+0100] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=execute, task_id=taskC, execution_date=20231016T000000, start_date=20231017T124019, end_date=20231017T124029
[2023-10-17T13:40:29.399+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 319 for task taskC (Bash command failed. The command returned a non-zero exit code 130.; 48176)
[2023-10-17T13:40:29.404+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-17T13:40:29.417+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
