[2023-10-16T13:27:41.034+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_sqlite_pipeline.insert_data2 manual__2023-10-16T12:27:37.183613+00:00 [queued]>
[2023-10-16T13:27:41.037+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_sqlite_pipeline.insert_data2 manual__2023-10-16T12:27:37.183613+00:00 [queued]>
[2023-10-16T13:27:41.037+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-16T13:27:41.041+0100] {taskinstance.py:1382} INFO - Executing <Task(SqliteOperator): insert_data2> on 2023-10-16 12:27:37.183613+00:00
[2023-10-16T13:27:41.042+0100] {standard_task_runner.py:57} INFO - Started process 91070 to run task
[2023-10-16T13:27:41.045+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'execute_sqlite_pipeline', 'insert_data2', 'manual__2023-10-16T12:27:37.183613+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/sqlite_pipeline.py', '--cfg-path', '/var/folders/_3/bj8r7kz51nz4g7hl_dpr6jdw0000gn/T/tmpbj78tu_k']
[2023-10-16T13:27:41.046+0100] {standard_task_runner.py:85} INFO - Job 91: Subtask insert_data2
[2023-10-16T13:27:41.060+0100] {task_command.py:416} INFO - Running <TaskInstance: execute_sqlite_pipeline.insert_data2 manual__2023-10-16T12:27:37.183613+00:00 [running]> on host 192.168.1.112
[2023-10-16T13:27:41.083+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='workflow' AIRFLOW_CTX_DAG_ID='execute_sqlite_pipeline' AIRFLOW_CTX_TASK_ID='insert_data2' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T12:27:37.183613+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-16T12:27:37.183613+00:00'
[2023-10-16T13:27:41.084+0100] {sql.py:274} INFO - Executing: 
            INSERT INTO new_users (name, age) VALUES
                ('Seun', 23),
                ('Ali', 25),
                ('Tunde', 27),
                ('Muna', 21);
        
[2023-10-16T13:27:41.086+0100] {base.py:73} INFO - Using connection ID 'db_sqlite_conn' for task execution.
[2023-10-16T13:27:41.114+0100] {base.py:73} INFO - Using connection ID 'db_sqlite_conn' for task execution.
[2023-10-16T13:27:41.114+0100] {sql.py:418} INFO - Running statement: 
            INSERT INTO new_users (name, age) VALUES
                ('Seun', 23),
                ('Ali', 25),
                ('Tunde', 27),
                ('Muna', 21);
        , parameters: None
[2023-10-16T13:27:41.114+0100] {sql.py:427} INFO - Rows affected: 4
[2023-10-16T13:27:41.117+0100] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=execute_sqlite_pipeline, task_id=insert_data2, execution_date=20231016T122737, start_date=20231016T122741, end_date=20231016T122741
[2023-10-16T13:27:41.151+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-16T13:27:41.158+0100] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
